### ISSUE TITLE
FileReference with broken link breaks API

### ISSUE THREAD

**Issue by TokeHerkild** [sourcebroker/t3api#60] opened 2022-01-24 10:34 UTC
If you have a model which has a list of FileReferences, then a missing file will cause the parent object to fail being loaded.

A fileReference with a missing/broken link will throw an Exception, not just report a broken link. This might be good behavier some places, but it does block the API from ever fixing the missing/broken link.

Tested with 1.2.3 and branch:issue-22 for TYPO3 10.4

**Comment by klamparski** [comment] 2022-01-26 05:55
Hi @TokeHerkild. Thanks for reporting the issue. I agree it should not throw an exception. If you are able please add to the issue exception details and configuration of your property (annotations). Then it will be easier to reproduce (I tried quickly with Image serialization and didn't get exception).

**Comment by klamparski** [comment] 2022-02-01 22:17
Thanks @TokeHerkild. Am I right that it occurs only when it's removed from `sys_file` table? I think I've tested it only by removing it from filesystem but kept it in `sys_file`. That could be a reason why I couldn't reproduce that. Will try to dive into it asap.

**Comment by kszymukowicz** [comment] 2024-05-07 19:48
Tnx for pointing this out.
Should be fixed with https://github.com/sourcebroker/t3api/commit/b2f4c63af0f8609d93ada46f8e777e6966f8f9b9

**Closed by kszymukowicz** 2024-05-07 19:48 UTC
