### ISSUE TITLE
[BUG] Concurrent API calls break due to meta-data writing/loading is not "thread safe". Only development mode.

### ISSUE THREAD

**Issue by avenit-martin-schulz** [sourcebroker/t3api#97] opened 2024-09-06 08:02 UTC
### TYPO3 version

11.5

### PHP version

8.1.26

### Extension version

2.0.3

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

DDEV on macOS 14.6.1

### Current behavior

Uppon concurrent requests to the API one of them regularly breaks since it cannot load meta data from cached .yaml file.

### Expected behavior

Concurrent request should be handled correctly

### Steps to reproduce

1. setup an api
2. call the api concurrently (10 parallel, for example via fetch() in FE)

-->repeating step (2) a couple of times shows that in average for 80% of the iterations at least one of the 10 calls breaks

### Additional context

When calling the API via route, meta data is first stored in a cached .yaml file in

`SerializerMetadataService::generateAutoloadForClass`

and later loaded in

`YamlDriver::generateAutoloadForClass`

Since storing the data uses `file_put_content` it is not safe uppon multiple concurrent requests.

If one request is storing the data and an other is loading it at the same time, it might get an empty file since `file_put_content` internally stores the file as empty before putting the actual content in it. 

Trying with the following code in `SerializerMetadataService::generateAutoloadForClass`, fixes the issue for me

```
// old
file_put_contents( 
  $generatedMetadataFile,
  Yaml::dump([$reflectionClass->getName()=>$classMergedMetadata], 99)
);
```

```
// new
$tmpFile=$generatedMetadataFile.'.'.uniqid();
file_put_contents(
  $tmpFile,
  Yaml::dump([$reflectionClass->getName()=>$classMergedMetadata], 99)
);
rename($tmpFile, $generatedMetadataFile);
```

Sadly I cannot properly overwrite the code since it a chain of `static` calls, thus a bugfix is very much required

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by klamparski** [comment] 2024-09-06 08:57
@avenit-martin-schulz As I remember I have faced that issue in the past but never pay so big attention to resolve it because it occurs on development environemnt (where we rebuild metadata for every request). Could you please confirm that is the case also for you and that you are not able to reproduce it on production?

Of course I don't mean it shouldn't be fixed - it should be done to work fine also on development environment, but I just want to ensure it's the same issue I faced in the past.

**Comment by kszymukowicz** [comment] 2024-09-21 12:56
@avenit-martin-schulz 

Tnx for finding this issue!

Your change is already on main branch (https://github.com/sourcebroker/t3api/pull/103) and will be released in bugfix release for 3.x next week.


As far as I see you use 2.x. We support 2.x only for critical issues and this issues is not critical from our point of view :)

You can always use https://github.com/cweagans/composer-patches
Or make a fork and then:
```
composer config repositories.sourcebroker/t3api vcs https://github.com/your_account/t3api
```

**Closed by kszymukowicz** 2024-09-21 12:56 UTC
Labels: bug
